version: '3.2'
services:
  consignment-service:
    build: ./consignment-service
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - consignment-service

  vessel-service:
    build: ./vessel-service
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"


