FROM golang:alpine as builder

RUN apk --no-cache add git

COPY . /go/src/github.com/clarkkkent/services/consignment-service

RUN go mod download

WORKDIR /go/src/github.com/clarkkkent/services/consignment-service

RUN go get -v

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o consignment-service .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /go/src/github.com/clarkkkent/services/consignment-service .

CMD ["./consignment-service"]